FROM python:3.11

RUN apt-get update && apt-get upgrade && apt-get install -y \
	libpcap0.8-dev \
	libuv1-dev

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --upgrade pip setuptools wheel pip-tools

COPY scripts/requirements.in requirements.in
RUN pip-compile --output-file=requirements.txt requirements.in
RUN pip install -r requirements.txt

COPY scripts/prueba_consumer.py .

CMD python3 prueba_consumer.py