FROM "bitnami/kafka:latest"

ENV KAFKA_CFG_NODE_ID=0
ENV KAFKA_CFG_PROCESS_ROLES=controller,broker
ENV KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
ENV KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
ENV KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
ENV N_PARTITIONS_PER_TOPIC=2

EXPOSE 9094

CMD ["sh", "-c", "kafka-topics.sh --bootstrap-server localhost:9092 --topic inference_data --create --partitions 2 --replication-factor 1 && kafka-topics.sh --bootstrap-server localhost:9092 --topic inference_probs --create --partitions 2 --replication-factor 1 && kafka-topics.sh --bootstrap-server localhost:9092 --topic predicted_labels --create --partitions 2 --replication-factor 1"]

#CMD ["sh", "-c", "/usr/local/bin/create-topics.sh & /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh"]

